### ISSUE TITLE
No way of showing "full" image on small screen

### ISSUE THREAD

**Issue by pseudomonas** [aerohub/hugrid#8]
Expanding a thumbnail on a small screen leads to showing the title/description/button, but no full image (or link to full image or anything.) This seems to be the case both on mobile devices and on desktop windows sized to be narrow.

**Comment by rlingineni** [comment]
+1

**Comment by charly3pins** [comment]
Hi,
I've checked the css that is used for show/hide the detail image and it's using @media queries.
This code is the specific one:
```css
@media screen and (max-width: 650px) {
	.og-fullimg { display: none; }
	.og-details { float: none; width: 100%; }	
}
```
So, you can create your custom css in a new file (f.e.: css/extra1.css) and add this block there:
```css
@media screen and (max-width: 650px) {
	.og-fullimg {
		display: block !important;
	}
	.og-details {
		float: left !important;
		width: 50% !important;
	}
}
```
You can also modify the width and the text display etc.. but this is the main idea. 

Hope it helps.
